### PR TITLE
Fix get_league_listing and return the status code 

### PR DESCRIPTION
**Pull request by Andryas**
I'm using this package to develop a package that provides a easy way to collect the Dota2 data and store in MongoDB. But I need to force the function (core.R) because it return an error. So, what I did was return a NULL content instead of an error. So I can check the status code and verify if it was connection error, many requests etc ... and decides what to do...

The second change was the function get_leangue_listings that was has a problem with the do.call(rbind....) because the diferent number of columns... so I change to plyr::rbind.fill.

### CODE REVIEW

**Comment by LyzandeR** [comment]
Thanks for the PR @Andryas . I ll have a look over the weekend.

**Comment by LyzandeR** [comment]
The PR fails the R CMD Check. Please make sure you check the package so that future releases are not problematic. This needs to be updated before I merge.

1. I agree with the `rbindlist` change.
2. I find the change in `get_league_listings` not very significant as the user can do that. I decided to keep one more level of data just in case Valve add any information there.
3. For future PRs, please try to keep code formatting changes to a minimum, because it becomes very difficult to check the differences.
4. Thank you very much for taking the time to submit the PR :)

**Comment by Andryas** [comment]
Hi, I am closing this PR because I preferred to reset my branch and follow your suggestions. Thanks!

**Comment by LyzandeR** [comment]
No problem, Feel free to resubmit afterwards!

**Pull request closed without merging**
